# Generated by Django 2.2.7 on 2019-11-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('sandwich', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('bread', models.CharField(max_length=20)),
                ('sauce', models.CharField(max_length=100)),
            ],
        ),
    ]
